name: "Fetch Skeleton Upstream"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  rebase-skeleton:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: upstream

      - run: git remote add skeleton https://github.com/teeframe/ddnet-skeleton
      - run: git fetch skeleton
      - run: git rebase skeleton/main
      - run: git push origin HEAD:upstream